name: ec2-env
dependencies:
- python>=3.5
- anaconda
- pip
- pip:
  # works for regular pip packages
  - torch==2.0
  - transformers==4.28.1
  - torchvision
  - numpy==1.24.3
  - tqdm
  - tensorboard>=1.14
  - pandas==2.0.1
  - datasets==2.12.0
  # and for wheels
  - http://www.lfd.uci.edu/~gohlke/pythonlibs/bofhrmxk/opencv_python-3.1.0-cp35-none-win_amd64.whl